[project]
name = "zertz3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "e2cnn>=0.2.1",
    "numpy>=2.3.3",
    "panda3d>=1.10.15",
    "panda3d-simplepbr>=0.12.0",
    "torch>=2.8.0",
    "torch-geometric>=2.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
